import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { SKETCHES } from '../sketchesMetadata'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GenArt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Arte Generativa</h1>
        </div>
        <div className={styles.subtitles}>
          <p>feito com p5.js</p>
          <p><Link href='https://github.com/Pitossomo' target='_blank'>por @Pitossomo</Link></p>
        </div>
        <div className={styles.grid}>
          { SKETCHES.map(s => (
            <Link key={s.url} href ={`/arts/${s.url}`} className={styles.card}>
              <h2 className={inter.className}>
                { s.title } 
                <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                { s.description }
              </p>
            </Link>
          ))}
        </div>
      </main>
    </>
  )
}

