import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GenArt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Arte Generativa</h1>
          <br />
          <p>com p5.js</p>
        </div>

        <div className={styles.grid}>
          <Link
            href="/arts/fibonacciTree"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Árvore de Fibonacci <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Ramificações crescentes e sucessivas partindo de um único ponto
            </p>
          </Link>

          <Link
            href="/arts/inscribedPolygons"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Polígonos Inscritos <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Polígonos inscritos sucessivamente entre si
            </p>
          </Link>

          <Link
            href="/arts/linesMovement"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Linhas em movimento <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Segmentos de retas em movimento aleatório
            </p>
          </Link>

          <Link
            href="/arts/spiral"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Espiral <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Lugar geométrico dos pontos com ângulo e distância crescentes em relação à origem
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}

